name: Service Build

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: BLOCKCHAIN-1 Update & Start
        run: ssh ${{ secrets.BLOCKCHAIN_USR }}@${{ secrets.BLOCKCHAIN1_HOST }} "cd ${{ secrets.BLOCKCHAIN_PATH }} && ./runner.sh"
      - name: BLOCKCHAIN-2 Update & Start
        run: ssh ${{ secrets.BLOCKCHAIN_USR }}@${{ secrets.BLOCKCHAIN2_HOST }} "cd ${{ secrets.BLOCKCHAIN_PATH }} && ./runner.sh"
      - name: BLOCKCHAIN-2 Update & Start
        run: ssh ${{ secrets.BLOCKCHAIN_USR }}@${{ secrets.BLOCKCHAIN3_HOST }} "cd ${{ secrets.BLOCKCHAIN_PATH }} && ./runner.sh"
  notify:
   name: Discord Notification
    runs-on: self-hosted
    needs:
      - build
    if: ${{ always() }}
    steps:
     - name: Notify
        uses: nobrayner/discord-webhook@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          discord-webhook: ${{ secrets.DISCORD_WEBHOOK_URL }}
